Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	plot_emission
	1

[Wed Dec 22 20:19:42 2021]
rule plot_emission:
    input: /mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz_highDiversity/contam0/inbred1/run57/coverage0.2/asc0/inputMode_hapProbs_fil0/hmm_parameters/p1_file.gz, /mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz_highDiversity/contam0/inbred1/run57/coverage0.2/asc0/inputMode_hapProbs_fil0/remHighdiv_diff.csv.gz, /mnt/diversity/divyaratan_popli/100arc/inbreeding/fastsim_gz_highDiversity/contam0/inbred1/run57/coverage0.2/asc0/inputMode_hapProbs_fil0/remHighdiv_total.csv.gz, dataf/contam0_inbred1_run57_coverage0.2_asc0_inputMode_hapProbs_fil0_B1file_0_15_relid, dataf/contam0_inbred1_run57_coverage0.2_asc0_inputMode_hapProbs_fil0_B2file_0_15_relid, dataf/contam0_inbred1_run57_coverage0.2_asc0_inputMode_hapProbs_fil0_xnew1file_0_15_relid, dataf/contam0_inbred1_run57_coverage0.2_asc0_inputMode_hapProbs_fil0_xnew2file_0_15_relid
    output: plots/contam0_inbred1_run57_coverage0.2_asc0_inputMode_hapProbs_fil0_pair0_15_relid_emissions_bnds.png
    jobid: 0
    wildcards: cnt=0, inb=1, RID=57, cov=0.2, asc=0, inpMode=hapProbs, Mfil=0, listind=0_15, rel=id

[Wed Dec 22 20:19:43 2021]
Error in rule plot_emission:
    jobid: 0
    output: plots/contam0_inbred1_run57_coverage0.2_asc0_inputMode_hapProbs_fil0_pair0_15_relid_emissions_bnds.png

RuleException:
CalledProcessError in line 157 of /mnt/diversity/divyaratan_popli/100arc/inbreeding/model_git/supplementary_info/Snakefile:
Command 'set -euo pipefail;  Rscript --vanilla /mnt/diversity/divyaratan_popli/100arc/inbreeding/model_git/supplementary_info/.snakemake/scripts/tmptppvq054.emission_bnds.R' returned non-zero exit status 1.
  File "/mnt/diversity/divyaratan_popli/100arc/inbreeding/model_git/supplementary_info/Snakefile", line 157, in __rule_plot_emission
  File "/home/divyaratan_popli/.conda/envs/relcap_env/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/diversity/divyaratan_popli/100arc/inbreeding/model_git/supplementary_info/.snakemake/log/2021-12-22T201939.889759.snakemake.log
